version: "2.2"

services:
  db:
    image: postgres:16
    container_name: ${POSTGRES_CONTAINER_NAME_TEST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_TEST}"]
      interval: 2s
      timeout: 1s
      retries: 10

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file: .env
    environment:
      RAILS_ENV: test
    volumes:
      - .:/app:cached
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        bundle exec rails db:create db:migrate &&
        bundle exec rspec
      "
