default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: segarante_api_development

test:
  <<: *default
  database: segarante_api_test

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV['POSTGRES_HOST'] %>
    database: <%= ENV['POSTGRES_DB'] %>
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
  cache:
    <<: *primary_production
    database: segarante_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: segarante_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: segarante_api_production_cable
    migrations_paths: db/cable_migrate
