default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: segarante_api_development

test:
  <<: *default
  database: segarante_api_test

production:
  primary: &primary_production
    <<: *default
    database: segarante_api_production
    username: segarante_api
    password: <%= ENV["SEGARANTE_API_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: segarante_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: segarante_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: segarante_api_production_cable
    migrations_paths: db/cable_migrate
